name = "MergedArrays"
uuid = "4201acb4-6ad2-4fbc-ab19-c24116385dd7"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "0.2.1"

[deps]
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"

[compat]
ArraysOfArrays = "0.6"
ConstructionBase = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
