name = "MergedArrays"
uuid = "4201acb4-6ad2-4fbc-ab19-c24116385dd7"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "0.1.2"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"

[compat]
ConstructionBase = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
