name = "MergedArrays"
uuid = "4201acb4-6ad2-4fbc-ab19-c24116385dd7"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"

[compat]
ConstructionBase = "1.5.8"
EllipsisNotation = "1.8.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
